version: '3.4'

services:
  node-red:
    image: nodered/node-red
    ports:
        - 1880:1880
    volumes:
        - node-red_data:/data
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:arm32v6
    volumes:
        - zigbee2mqtt_config:/app/data
    devices:
        - "/dev/ttyACM0"
  mqtt:
    image: eclipse-mosquitto
    ports:
        - 1883:1883
        - 9001:9001
    container_name: mqtt
    volumes:
        - mosquitto_config:/mosquitto/config/mosquitto.conf
        - mosquitto_data:/mosquitto/data
        - mosquitto_log:/mosquitto/log
    
volumes:
  node-red_data: {}
  zigbee2mqtt_config: {}
  mosquitto_config: {}
  mosquitto_data: {}
  mosquitto_log: {}